// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBr75Hqz4LbzwKRRnOWiB1HGdeO42irMYw",
    appId: '1:804223450200:web:93e957a4647d8d8a1c5e2d',
    messagingSenderId: '804223450200',
    projectId: 'harsat-1f4d3',
    authDomain: 'harsat-1f4d3.firebaseapp.com',
    databaseURL:
        'https://harsat-1f4d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'harsat-1f4d3.appspot.com',
    measurementId: 'G-F1LF3VPJEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr75Hqz4LbzwKRRnOWiB1HGdeO42irMYw',
    appId: '1:804223450200:android:0693aaf835944df21c5e2d',
    messagingSenderId: '804223450200',
    projectId: 'harsat-1f4d3',
    databaseURL:
        'https://harsat-1f4d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'harsat-1f4d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSj8xZ4enOiMp9WDmts0_5N7i2h-iD520',
    appId: '1:804223450200:ios:3895bed4ef35e89c1c5e2d',
    messagingSenderId: '804223450200',
    projectId: 'harsat-1f4d3',
    databaseURL:
        'https://harsat-1f4d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'harsat-1f4d3.appspot.com',
    iosClientId:
        '804223450200-3odhsjhds9rv17fos633pgr00d5emnc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.harsatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSj8xZ4enOiMp9WDmts0_5N7i2h-iD520',
    appId: '1:804223450200:ios:3895bed4ef35e89c1c5e2d',
    messagingSenderId: '804223450200',
    projectId: 'harsat-1f4d3',
    databaseURL:
        'https://harsat-1f4d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'harsat-1f4d3.appspot.com',
    iosClientId:
        '804223450200-3odhsjhds9rv17fos633pgr00d5emnc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.harsatapp',
  );
}
